apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-operations
spec:
  selector:
    matchLabels:
      app: mongo-operations
  template:
    metadata:
      labels:
        app: mongo-operations
    spec:
      containers:
        - name: mongo-operations
          image: dhs2112.azurecr.io/mongo-operations
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
