name: Maven Build

on:
  push:
    branches: [ main, feature/*, fix/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Test with Maven
      run: mvn test
    - name: Build with Maven
      run: mvn clean -B package --file pom.xml

