name: Maven Build

on:
  push:
    branches: [ main, feature/*, fix/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Test with Maven
      run: mvn test
    - name: Calculate next version
      run: |
        export MINOR_VERSION=$($(echo date +"%y"))$(WEEK=$((10#$(date +"%V")+1)); if [ $(($WEEK%2)) -eq 0 ]; then if [ ${#WEEK} = 1 ]; then echo "0${WEEK}"; else echo $WEEK; fi; else WEEK=$(($WEEK -1)); if [ ${#WEEK} = 1 ]; then echo "0${WEEK}"; else echo $WEEK; fi; fi)
        export MAJOR_VERSION=1
        export ACTUAL_VERSION="$MAJOR_VERSION.$MINOR_VERSION.1"
        echo $ACTUAL_VERSION
    - name: Build with Maven
      run: mvn -Drevision=$ACTUAL_VERSION jar:jar spring-boot:repackage

