name: Build & Push Docker image to ACR

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Dependency to a forking workflow
  workflow_run:
    workflows: ["Maven Build"]
    type:
      - complete

env:
  REGISTRY_NAME: dhs2112
  CLUSTER_NAME: test-cluster
  CLUSTER_RESOURCE_GROUP: spring-boot-rg
  APP_NAME: mongo-operations

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    # Connect to Azure Container Registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    # Container build and push to a Azure Container Registry (ACR)
    - run: |
        export MINOR_VERSION=$($(echo date +"%y"))$(WEEK=$((10#$(date +"%V")+1)); if [ $(($WEEK%2)) -eq 0 ]; then if [ ${#WEEK} = 1 ]; then echo "0${WEEK}"; else echo $WEEK; fi; else WEEK=$(($WEEK -1)); if [ ${#WEEK} = 1 ]; then echo "0${WEEK}"; else echo $WEEK; fi; fi)
        export MAJOR_VERSION=1
        export ACTUAL_VERSION=$MAJOR_VERSION.$MINOR_VERSION.1
        echo $ACTUAL_VERSION
        docker build -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:1.0 .
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:1.0
      #working-directory: .
